controller_manager:
  ros__parameters:
    update_rate: 10 # Hz
    use_sim_time: true # For simulated robots

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    ackermann_steering_controller:
      type: ackermann_steering_controller/AckermannSteeringController


ackermann_steering_controller:
  ros__parameters:
    reference_timeout: 2.0
    front_steering: true
    open_loop: false
    velocity_rolling_window_size: 10
    position_feedback: true

    use_stamped_vel: false

    front_wheels_names: ["robot_left_steering_joint", "robot_right_steering_joint"]
    rear_wheels_names: ["robot_left_rear_axle", "robot_right_rear_axle"]

    wheelbase: 1.83323 # Distance between the front and rear axles (from suspension_wheel_v3.urdf.xacro)
    front_wheel_track: 1.24248 # Distance between left and right front wheels (2 * wheel_offset_y)
    rear_wheel_track: 1.24248 # Distance between left and right rear wheels (2 * wheel_offset_y)
    front_wheels_radius: 0.3195 # Radius of the wheels (tire_dia/2)
    rear_wheels_radius: 0.3195 # Radius of the wheels (tire_dia/2)
    wheel_separation: 1.24248 # Same as track width
    max_steering_angle: 0.785 # PI/4 radians (45 degrees) from URDF limits
    min_steering_angle: -0.785 # -PI/4 radians (-45 degrees) from URDF limits

    steering_slow_down_factor: 1.5 #1.0 no slowdown
    angular_velocity_filter: 0.3

    enable_odom_tf: true
    odom_frame_id: odom
    base_frame_id: base_link
    cmd_vel_topic: "cmd_vel"
    cmd_type: "geometry_msgs/msg/Twist"

    publish_rate: 50


    # NOISE ---------------------------------------------------------------------------------
    # Overall uncertainty in the odometry estimation based on the robot's kinematic model 
    
    #pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01] #higher uncertainty in yaw
    #twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01] #higher uncertainty in yaw
    
    # Gaussian noise
    #gaussian_noise:
    #  linear:
    #    x:
    #      stddev: 0.1  # Standard deviation for linear x velocity noise
    #      mean: 0.0     # Mean of the noise (kept at 0 to avoid bias)
    #  angular:
    #    z:
    #      stddev: 0.1  # Standard deviation for angular z velocity noise
    #      mean: 0.0

    